name: First Workflow

on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - name: simple echo command
       run: echo "Welcome To GitHub Action"
     - name: running multiple commands
       run: |
          echo "Hello World"
          echo "Hello India"
          sudo apt update -y
          sudo apt install apache2 -y
          sudo systemctl start apache2
          curl localhost   